LEARNING_RATE = 0.00005
NUM_SAMPLES = 25000000
EPOCHS = 1
WORDLE_WEIGHTS = "wordle_weights.npy"
PAIR_WEIGHTS = "pair_weights.npy"
BIGRAM_FACTOR = 1.0
PAIR_MULTIPLIER = 1.2
WORDS_MATRIX = "words_matrix.npy"